[package]
name = "checkpointer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
futures-util = "0.3.30"
reqwest = "0.11.23"
reqwest-eventsource = "0.5.0"
serde.workspace = true
serde_json = "1.0.113"
tokio = { version = "1.35.1", default-features = false, features = ["macros", "sync"] }
tracing-actix-web = "0.7.6"
tracing = "0.1.37"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
thiserror = "1.0.56"

[dev-dependencies]
wiremock = "0.6.0-rc.2"
